version: "3.9"

services:
  postgres:
    image: timescale/timescaledb-ha:pg17.7-ts2.24.0
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_partman_bgw,timescaledb"
      - "-c"
      - "pg_partman_bgw.interval=3600"
    restart: no

volumes:
  postgres-data:
